repos:
  - repo: local
    hooks:
      - id: generate-tests
        name: Generate Tests
        entry: python generate_tests.py
        language: system
        types: [python]
        pass_filenames: false
        files: ^src/
        verbose: true
        always_run: true
